model_list:
  - model_name: local
    litellm_params:
      model: ollama_chat/qwen3-coder:30b
      api_base: os.environ/OLLAMA_HOST_URL

  - model_name: local-chat
    litellm_params:
      model: ollama_chat/qwen3.8:27b-q8_0
      api_base: os.environ/OLLAMA_HOST_URL

litellm_settings:
  drop_params: true

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
